on:
  repository_dispatch:
    types: [test]

name: test

env:
  repo: '${{ github.event.client_payload.repo }}'
  jimmy: 'jimmy'

jobs:
  print-vars-1:
    runs-on: ubuntu-latest
    if: contains(github.event.client_payload.repo, 'ahmed')
    name: show vars one
    steps:
      - name: print vars one
        run: |
          echo repo_name = ${{ env.repo }}

  print-vars-2:
    runs-on: ubuntu-latest
    if: contains(github.event.client_payload.repo, 'jenkins_nodejs')
    name: show vars two
    steps:
      - name: print vars two
        run: |
          echo jimmy = ${{ env.jimmy }}
        
