on:
  repository_dispatch:
    types: [test]

name: test

env:
  repo: '${{ github.event.client_payload.repo }}'

jobs:
  print-vars:
    runs-on: ubuntu-latest
    if: ${{ github.event.client_payload.repo }} == "muhammedgamal760/jenkins_nodej"
    name: show vars
    steps:
      - name: print vars
        run: |
          echo repo_name = ${{ env.repo }}
        
