on:
  repository_dispatch:
    types: [test]

name: test

env:
  repo: '${{ github.event.client_payload.repo }}'

jobs:
  print-vars:
    runs-on: ubuntu-latest
    name: show vars
    steps:
      - name: print vars
        if: ${{ ${env.repo} == "Salt" }}
        run: |
          echo repo_name = ${{ env.repo }}
        
