on:
  repository_dispatch:
    types: [test]

name: test

env:
  repo: '${{ github.event.client_payload.repository.name }}'

jobs:
  print-vars:
    runs-on: ubuntu-latest
    if: ${{ env.repo }} == "jenkins_nodejs"
    name: show vars
    steps:
      - name: print vars
        run: |
          echo repo_name = ${{ env.repo }}
        
